### ISSUE TITLE
Issues with conceptualising the code

### ISSUE THREAD

**Issue by caramel-koala** [landmanbester/Simple_CS#3]
I'm just having some issues in switching between the Primal Dual's f(x)+g(Lx) notation and the other notation (FI_D - FI)^+. I think part of the reason is that I don't know what the second is called so reading up on it is a bit difficult. Could you help with this please?

**Comment by landmanbester** [comment]
The second part just replaces the old likelihood function, everything else remains the same. So where the old g(Lx) projects onto the noise ball of the visibilities the new one just projects onto the noise ball of the dirty image. Let's discuss via hangouts on Monday
